apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: arafat1998/complex-worker:v1.0
      ports:
        - containerPort: 3000
